define(function() {
    return {
        STARTING_CIRCLES_QUANTITY: 3,
        SPLASH_SCREEN_DURATION: 3500,
        OUTLINE_CIRCLE_STROKE: 1,
        OUTLINE_CIRCLE_RADIUS: 50,
        NEW_CIRCLE_ANIMATION_SPEED: 500,
        POP_CIRCLE_ANIMATION_SPEED: 100
    };
});